version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

commands:
  system_info:
    steps:
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn -v)"
  setup:
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup
          command: yarn setup
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn


jobs:
  build:
    executor:
      name: default
    steps:
      - system_info
      - checkout
      - setup
      - run:
          name: Build
          command: |
            yarn build --stage dev
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./*
  deploy:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Deploy
          command: |
            yarn deploy --stage dev


workflows:
  build-deploy-flow:
    jobs:
      - build:
          context: rap-tap-app
      - deploy:
          context: rap-tap-app
          requires:
            - build
          filters:
            branches:
              only:
                - master
