version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

commands:
  attach:
    steps:
      - attach_workspace:
          at: .
  persist:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - "*"

jobs:
  setup:
    executor: default
    steps:
      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn -v)"
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup
          command: |
            yarn setup
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist
  lint:
    executor: default
    steps:
      - attach
      - run:
          name: Lint
          command: |
            yarn lint --format junit --output-file reports/eslint/results.xml
      - store_artifacts:
          path: reports
      - store_test_results:
          path: reports
  build:
    executor: default
    steps:
      - attach
      - run:
          name: Build
          command: |
            yarn build
  deploy:
    executor: default
    parameters:
      stage:
        type: enum
        enum: [ "none", "dev" ]
    steps:
      - attach
      - deploy:
          command: |
            yarn deploy --stage << parameters.stage >>


workflows:
  build-deploy-flow:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          context: rap-tap-app
          requires:
            - setup
      - deploy:
          stage: none
          context: rap-tap-app
          requires:
            - lint
            - build
          filters:
            branches:
              ignore: master
      - deploy:
          stage: dev
          context: rap-tap-app
          requires:
            - lint
            - build
          filters:
            branches:
              only: master
